version: '3'
services:

  web:
    build: ./app    #build from the Dockerfile in current directory.
    ports:
     - "2344:2344"
    volumes:
     - ./app:/app  #mounts project directory to on the host to /app inside the container.
    environment:
      - ENV=development
